name: Electron Production Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    env:
      server-working-directory: server
      electron-working-directory: server\release-to-production\electron-package

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read node version
        id: nvmrc
        uses: juliangruber/read-file-action@v1
        with:
          path: ./${{ env.server-working-directory }}/.nvmrc

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.nvmrc.outputs.content }}

      - name: Install server dependencies
        run: npm install
        working-directory: ${{ env.server-working-directory }}

      - name: Install electron dependencies
        run: npm install
        working-directory: ${{ env.electron-working-directory }}

      - name: Run client build
        run: npm run build:client
        working-directory: ${{ env.server-working-directory }}

      - name: Run electron build
        run: npm run build
        working-directory: ${{ env.electron-working-directory }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: electron-dist
          path: ./${{ env.electron-working-directory }}/electron-dist.zip
#   release:
#     needs: build
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Download artifact
#         uses: actions/download-artifact@v4
#         with:
#           name: release-to-production

#       - name: Read Environment variables
#         id: dotenv
#         uses: falti/dotenv-action@v1
#         with:
#           path: server/src/configs/.env

#       - name: Rename artifact
#         run: mv release-to-production.zip softwarePracticesMetricsTool-V${{ steps.dotenv.outputs.PRODUCTION_DOCKER_IMAGE_VERSION }}.zip

#       - name: Delete existing release with version {${{ steps.dotenv.outputs.PRODUCTION_DOCKER_IMAGE_VERSION }}}
#         uses: cb80/delrel@latest
#         with:
#           tag: ${{ steps.dotenv.outputs.PRODUCTION_DOCKER_IMAGE_VERSION }}
#           token: ${{ secrets.GITHUB_TOKEN }}

#       - name: Create Release
#         uses: ncipollo/release-action@v1
#         with:
#           tag: ${{ steps.dotenv.outputs.PRODUCTION_DOCKER_IMAGE_VERSION }}
#           name: ${{ steps.dotenv.outputs.PRODUCTION_DOCKER_IMAGE_VERSION }}
#           artifacts: ./softwarePracticesMetricsTool-V${{ steps.dotenv.outputs.PRODUCTION_DOCKER_IMAGE_VERSION }}.zip
#           token: ${{ secrets.GITHUB_TOKEN }}
